name: Call a reusable workflow 

on:
  workflow_dispatch:
    inputs:
      client_repository:
        description: 'repository'
        required: true
      branch:
        description: 'branch'
        required: true
 
jobs:

  Deploy:
    
    uses: American-Chip/workflow-remote/.github/workflows/graviton-scan-reusable.yaml@main
    with:
      CLIENT_REPOSITORY: ${{ inputs.client_repository }
      BRANCH : ${{ inputs.branch }

      